### ISSUE TITLE
Dependecy and module not found.

### ISSUE THREAD

**Issue by LedZeck** [Nbsaw/Bronya#2]
I got two simple errors when tried to run the project locally. Could be nice fix this by changing two small things.

The first one is "Dependecy not found" on `./src/store/mutations.js`.
Solved by changing `import Vue from 'Vue'`
to
`import Vue from 'vue'`

Second one is  "This relative module was not found" on `./src/components/aside/Aside.vue`
Solved by changing `import AsideHeader from './header'`
to
`import AsideHeader from './Header'`

😄

**Comment by yuxino** [comment]
I didn't notice the mistake. Thank you @LedZeck !   ❤️   Have a nice day.

**Comment by Muzm** [comment]
❤️
