### ISSUE TITLE
老铁。。。install 就报错是几个意思啊 

### ISSUE THREAD

**Issue by gggso** [Nbsaw/Bronya#3]
崩溃啊

哭脸

**Comment by yuxino** [comment]
@gggso 我看看 这项目好久之前的啦 我clone下来看没有问题呀。你按下面流程试一下吧。

``` js
cd client
yarn
```

我的`package.json`没有丢在最外面噢。我猜你是在根目录下面`install`的吧。

**Comment by gggso** [comment]
@Nbsaw 谢啦。写了issues 才发现
